import = [
	# "~/.config/alacritty/themes/xterm.toml"
]

[font]
size = 18.0
offset = { x=0, y=1 }

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t@"

[window]
padding = { x=10, y=10 }
decorations = "Buttonless"
startup_mode = "Maximized"

[colors]
cursor = { text="#000000", cursor="#ffffff" }
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"
