[font]
size = 21.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
padding = { x=10, y=10 }
decorations = "Buttonless"
startup_mode = "Maximized"

[colors]
cursor = { text="#000000", cursor="#ffffff" }

[env]
TERM = "xterm-256color"
